### (week4) Classfication
> `aim`
> + クラスを利用したコードを読み書きできるようにする

> `Cf.`
> + [sklearn.preprocessing.StandardScaler — scikit-learn 0.21.3 documentation](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)
> 

##### - samplecode

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


#### 【問題1】これまで利用してきたクラスの列挙
> Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

>`Pandas`
> + DataFrame()
> + Serise()

>`matplotlib`
> + Figure
> + Axes

>`scikit-learn`
> + LogisticRegresion
> + SVM (SVR, SVC)

#### 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙
>      これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。
>      最低でもそれぞれ5つ以上答えてください。

> `メソッド`
> + sum()
> + min(), max()
> + valus().tolist()
> + sort_values()
> + loc[], iloc[]

> `インスタンス変数`
> + np.shape
> + np.dtype
> + pd.copy
> + pd.info
> + pd.columns

#### 【問題3】標準化クラスをスクラッチで作成
> `Cf.`
> + [分散の意味と二通りの計算方法 - 高校数学の美しい物語](https://mathtrain.jp/variance#ad)
> + [sklearn StandardScaler で標準化の効果を確かめる－python - コード７区](http://ailaby.com/scaler/#id1_1)
> + [標準偏差の意味と求め方 - 公式と計算例 - Sci-pursuit](https://sci-pursuit.com/math/statistics/standard-deviation.html)
> + [平方根（ルート）の計算や問題の解き方を完璧に理解しよう！](https://www.studyplus.jp/348)

> + [[source]](https://github.com/scikit-learn/scikit-learn/blob/7389dba/sklearn/preprocessing/data.py#L480)

In [2]:
# 計算フルスクラッチ
class ScratchStandardScaler_1():

    def fit(self, X):
        self.mean_ = sum(X) / len(X)
        self.var_ = sum((X - self.mean_)**2)/len(X)
        
    def transform(self, X):
        X_scaled = (X - self.mean_) / (self.var_ )**0.2
        
        return X_scaled

In [6]:
# NumPy
import numpy as np

class ScratchStandardScaler_2():

    def fit(self, X):
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.var(X, axis=0)
        
    def transform(self, X):
        X_scaled = (X - self.mean_) / np.std(X, axis=0)
        
        return X_scaled

In [7]:
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler_1()
scratch_scaler.fit(X)

print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.40141405  0.31115162 -0.12437473 -0.05641471]
 [ 0.06690234 -0.50766843 -0.12437473 -0.05641471]
 [-0.26760937 -0.18014041 -0.37312418 -0.05641471]
 [-0.43486522 -0.34390442  0.12437473 -0.05641471]
 [ 0.2341582   0.47491563 -0.12437473 -0.05641471]
 [ 0.90318161  0.96620765  0.62187364  0.50773243]
 [-0.43486522  0.14738761 -0.12437473  0.22565886]
 [ 0.2341582   0.14738761  0.12437473 -0.05641471]
 [-0.76937693 -0.67143244 -0.12437473 -0.05641471]
 [ 0.06690234 -0.34390442  0.12437473 -0.33848828]]


In [8]:
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler_2()
scratch_scaler.fit(X)

print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


#### 【問題4】 四則演算を行うクラスの作成

> (特殊メソッド) ```__init__``` コンストラクタの理解 

In [27]:
class ExampleClass():
    def __init__(self, value):
        if type(value) != int and type(value) != float :
            raise ValueError("Plz input 'int' or 'float' (Ŏ艸Ŏ)...")
        else:
            self.value = value
            print("初期値{}が設定されました".format(self.value))
        
    def add(self, value2):
        self.value += value2
        
    def pul(self, value3):
        self.value -= value3
        
    def mul(self, value4):
        self.value *= value4
        
    def div(self, value5):
        self.value /= value5

example = ExampleClass(5) # インスタンス
print("init value : {}".format(example.value)) # コンストラクタが呼び出された

example.add(3)
print("add value : {}".format(example.value)) # addメソッドが呼び出された
example.pul(3)
print("pul value : {}".format(example.value))
example.mul(3)
print("mul value : {}".format(example.value)) # addメソッドが呼び出された
example.div(3)
print("div value : {}".format(example.value)) # addメソッドが呼び出された

初期値5が設定されました
init value : 5
add value : 8
pul value : 5
mul value : 15
div value : 5.0


In [28]:
example = ExampleClass(5.0) # インスタンス
print("init value : {}".format(example.value)) # コンストラクタが呼び出された

初期値5.0が設定されました
init value : 5.0


In [29]:
example = ExampleClass("5") # インスタンス
print("init value : {}".format(example.value)) # コンストラクタが呼び出された

ValueError: Plz input 'int' or 'float' (Ŏ艸Ŏ)...