# (Week2) 📊 行列積


```線形代数 （Linear Algebra - リニアーアルジェブラ）```
> 線型空間と線型変換を中心とした理論を研究する代数学の一分野。 もう少し噛み砕いた言い方だと、行列の性質や扱い方を考えた学問と捉えても問題ない。

```🖋 memo```
+ 基本的な線形代数は、機械学習を学ぶ際の必要最低限の知識。
+ 機械学習では、PandasやNumpyで、データセット前処理として行列の演算などを行う。(「行列」の基本的な役割や扱い方の知識が必要。)
+ 機械学習で使われるアルゴリズムをより深く理解できる。
  - アルゴリズムの理解が深まれば、より深いレベルでのアルゴリズムの実装や、さらには正しい理解のもとチューニングを行うことも可能。
  - 線形代数を理解することで、機械学習で行えることや得られる結果に大きく幅を持つことが可能。


```Python
import numpy as np
a = np.array([[-1, 2, 3],
              [4, -5, 6],
              [7, 8, -9]])
b = np.array([[0, 2, 1],
              [0, 2, -8],
              [2, 9, -1]])
np.dot(a, b)
```

<hr>

## 【問題1】行列積を手計算する

```Cf.```
+ [Qiitaの数式チートシート](https://qiita.com/PlanetMeron/items/63ac58898541cbe81ada)
+ [LaTeXコマンド集](http://www.latex-cmd.com/)
+ [Cloud LaTeX | Build your own LaTeX environment, in seconds](https://cloudlatex.io/ja)

■ 行列積を求めよ

$
A = 
\begin{bmatrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9
\end{bmatrix}
\ ,
B = 
\begin{bmatrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1
\end{bmatrix}
$


`（STEP1）　Bの値を列で分割`

$
B_x = 
\begin{bmatrix}
0 \\
0 \\
2 
\end{bmatrix}
\
B_y =
\begin{bmatrix}
2 \\
2 \\
9 
\end{bmatrix}
\
B_z
\begin{bmatrix}
1 \\
-8 \\
-1 
\end{bmatrix}
$


`（STEP2）　スカラー倍のベクトル計算`

$
A \times B_x = AB_x\\
A \times B_y = AB_y\\
A \times B_z = AB_z
$

> ```e.g.```
>
>$
A \times B_x = AB_x \\
\begin{bmatrix}
-1 \times 0 \\
4 \times 0 \\
7 \times 0
\end{bmatrix}
\ +
\begin{bmatrix}
2 \times 0 \\
-5 \times 0 \\
8 \times 0
\end{bmatrix}
\ +
\begin{bmatrix}
3 \times 2 \\
6 \times 2 \\
-9 \times 2
\end{bmatrix}
\ =
\begin{bmatrix}
0 \\
0 \\
0
\end{bmatrix}
\
\begin{bmatrix}
0 \\
0 \\
0
\end{bmatrix}
\
\begin{bmatrix}
6 \\
12 \\
-18
\end{bmatrix}
\ = 
\begin{bmatrix}
6 \\
12 \\
-18
\end{bmatrix}
$

`（STEP３）其々のベクトルを足し合わせ行列に。`

$
AB_x + AB_y + AB_z 
$

```i.e.```
$ 
\begin{bmatrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48
\end{bmatrix}
$

<hr>

## 【問題2】NumPyの関数による計算


```Cf.```
+ [numpy.matmul — NumPy v1.16 Manual](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
+ [numpy.dot — NumPy v1.16 Manual](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
+ [numpyと、アダマール積 - mucun_wuxian(note)](https://note.com/mucun_wuxian/n/n9c8e0ed3c8a6)
+ [Python, NumPyで行列の演算（逆行列、行列式、固有値など） - note.nkmk.me](https://note.nkmk.me/python-numpy-matrix/)

2次元配列の行列積
> ```np.matmul()```、```@演算子```（公式推奨）

3次元以上の行列積
> ```np.dot()```、```np.matmul()```

In [1]:
import numpy as np

a = np.array([[-1, 2, 3],
              [4, -5, 6],
              [7, 8, -9]])
b = np.array([[0, 2, 1],
              [0, 2, -8],
              [2, 9, -1]])

In [ ]:
np.version.full_version

In [2]:
np.dot(a, b)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [3]:
np.matmul(a, b)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [4]:
a @ b

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

<hr>

## 【問題3】ある要素の計算を実装

$$
\sum_{k=0}^{2} a_{0,k} b_{k,0}
$$

In [13]:
res = []

for i in range(a.shape[0]):
    sum_list = []
    for j in range(a.shape[0]):
        sum = 0
        for k in range(a.shape[0]):
            sum += a[i, k]*b[k, j] # 0+0+6
            #print(sum)
        
        #print(sum)
        #print('-'*20)
        sum_list.append(sum)       # 6 29 -20
    #print(sum_list)
    res.append(sum_list)           # [6 29 -20]

back = np.array(res)
print(back)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


<hr>

## 【問題4】行列積を行う関数の作成

$$
c_{i,j} = 
\sum_{k=0}^{2} a_{i,k} b_{k,j}
$$

```Cf.```
+ [Matrix Factorization：Pythonでのチュートリアルと実装 - ENJOYWORKS](https://enjoyworks.jp/tech-blog/633)
+ [Python, zip関数の使い方: 複数のリストの要素をまとめて取得 - note.nkmk.me](https://note.nkmk.me/python-zip-usage-for/)

In [5]:
# 行列積を求める関数
def make_matrix(a, b):

    res = []

    for i in range(a.shape[0]):
        sum_list = []
        for j in range(a.shape[0]):
            sum = 0
            for k in range(a.shape[0]):
                sum += a[i, k]*b[k, j] # 0+0+6

            sum_list.append(sum)       # 6 29 -20
        res.append(sum_list)           # [6 29 -20]

    back = np.array(res)
    return back


In [26]:
x =  make_matrix(a, b)
print(x, x.shape, type(x))
x

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]] (3, 3) <class 'numpy.ndarray'>


array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

```memo```
for文での行列計算理解

<img src='https://t.gyazo.com/teams/diveintocode/129123df5242c9e768513f5e8b5ef24f.png' width=50% style="text-align:center;"/>


```Python
a[0,0]*b[0,0]
a[0,1]*b[1,0]  = 6
a[0,2]*b[2,0]

a[0,0]*b[0,1]
a[0,1]*b[1,1]  = 29
a[0,2]*b[2,1]

a[0,0]*b[0,2]
a[0,1]*b[1,2] = -20
a[0,2]*b[2,2]

a[1,0]*b[0,0]
a[1,1]*b[1,0]  = 12
a[1,2]*b[2,0]

a[1,0]*b[0,1]
a[1,1]*b[1,1]  = 52
a[1,2]*b[2,1]

a[1,0]*b[0,2]
a[1,1]*b[1,2] = 38
a[1,2]*b[2,2]
```

<hr>

## 【問題5】計算が定義されない入力を判定する

```Cf.```
+ [Pythonのif文による条件分岐の書き方 - note.nkmk.me](https://note.nkmk.me/python-if-elif-else/)

```memo```
+ 次元の異なるベクトル計算は不可。
>```e.g.```
>
>$
（計算可能）
\\
3row ３col
\begin{bmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{bmatrix}
3row 1col
\begin{bmatrix}
a \\
b \\
c
\end{bmatrix}
\,
\\
(計算不可)
\\
２row ４col
\begin{bmatrix}
a & b \\
c & d \\
e & f \\
g & h 
\end{bmatrix}
１row ４col
\begin{bmatrix}
a & b & c & d
\end{bmatrix}\\
この場合、「4row1col」なら可能
$

In [23]:
d = np.array([[-1, 2, 3], 
              [4, -5, 6]])
e = np.array([[-9, 8, 7], 
              [6, -5, 4]])

In [16]:
print(d.shape)
print(e.shape)

(2, 3)
(2, 3)


In [20]:
def make_matrix(a, b):
    if a.shape[1]!= b.shape[0]:
        print('[warnig] Different dimensions.')
    
    else :
        res = []

        for i in range(a.shape[0]):
            sum_list = []
            for j in range(a.shape[0]):
                sum = 0
                for k in range(a.shape[0]):
                    sum += a[i, k]*b[k, j] # 0+0+6

                sum_list.append(sum)       # 6 29 -20
            res.append(sum_list)           # [6 29 -20]

        back = np.array(res)
        return back

In [21]:
make_matrix(d, e)

[warnig] Different dimensions.


<hr>

## 【問題6】転置

In [22]:
make_matrix(d, e.T)

array([[ 25, -16],
       [-76,  49]])