In [ ]:
import numpy as np

a = np.array([[2,7],[1,8]])
b = np.array([[2,8],[1,3]])

c = np.dot(a, b)
d = a * b

print('ABの行列積')
print(c)
# [[11 37]
#  [10 32]]

print('ABのアダマール積')
print(d)
# [[ 4 56]
#  [ 1 24]]
 
print('ABの行列積の転置行列')
print(c.T)
# [[11 10]
#  [37 32]]

print('ABのアダマール積の転置行列')
print(d.T)
# [[ 4  1]
#  [56 24]]


In [ ]:
# try:
#     row_number = int(input())
# except ValueError:
#     row_number = 3

# for i in range(row_number):
for i in range(3):
    value = input().rstrip()
	pr = 'Your answer: ' 
	print(pr, value)

In [ ]:
def check_sample(l):
    try:
        i = [float(s) for s in l]
    except ValueError:
        i = [0]
    num_max = max(i)
    num_min = min(i)
    return num_max - num_min


T = int(input())
for i in range(T):
    values = input().rstrip().split(' ')
    # print(values)
    result = check_sample(values)
    # print('{:.1f}'.format(result))
    print(round(result, 1))

cf. [Pythonで文字列のリスト（配列）と数値のリストを相互に変換](https://note.nkmk.me/python-list-str-num-conversion/)