# NumPy

In [5]:
import numpy as np

sample_list = [1, 2, 3]
sample_ndarry = np.array([sample_list, [4, 5, 6]])
print(sample_ndarry, 'このNumPyの配列を ndarray と呼ぶ')

[[1 2 3]
 [4 5 6]] このNumPyの配列を ndarray と呼ぶ


In [6]:
# ndarrayを使わない場合、整数型とPythonのリストの足し算は定義されていないため、以下のコードはエラー
print(2 + [1, 2, 3])

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [8]:
# ブロードキャスト(Pythonリスト)
a = 2
b_list = [1, 2, 3]
c_list = []

for b in b_list:
    c_list.append(a+b)
    print(c_list)
print(c_list)

[3]
[3, 4]
[3, 4, 5]
[3, 4, 5]


In [16]:
# ブロードキャスト（Numpyリスト）
print(2 + np.array(b_list))
print(np.array([2]) + np.array([1, 2, 3])) #ブロードキャストされる
print(np.array([2, 2]) + np.array([1, 2, 3]))　#ブロードキャストされない

[3 4 5]
[3 4 5]


ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [12]:
# PythonのリストとPythonのリストの足し算もできません
print(np.array([b_list]) +np.array([c_list])) 

[[4 6 8]]


In [13]:
print(np.array([1, 2, 3]) * np.array([1, 2, 3])) # [1 4 9]
print(np.array([1, 2, 3]) > np.array([2, 2, 2])) # [False False  True]

[1 4 9]
[False False  True]


## 配列の情報

In [20]:
print(np.array([1, 2, 3]).ndim)  #次元数（n_dimenstion）
print(np.array([1, 2, 3]).shape) #形（行,列）
print(np.array([1, 2, 3]).dtype) #型（data_type）
print(type(np.array([1, 2, 3])))

1
(3,)
int64
<class 'numpy.ndarray'>


## 連番で配列を作成

In [21]:
sample_ndarray = np.arange(100)
print(sample_ndarray)
print(sample_ndarray.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)


In [22]:
sample_ndarray = np.array(range(100))
print(sample_ndarray)
print(sample_ndarray.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
(100,)


In [23]:
sample_ndarray = np.arange(50, 200, 2)
print(sample_ndarray)
print(sample_ndarray.shape)

[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100 102 104 106 108 110 112 114 116 118 120
 122 124 126 128 130 132 134 136 138 140 142 144 146 148 150 152 154 156
 158 160 162 164 166 168 170 172 174 176 178 180 182 184 186 188 190 192
 194 196 198]
(75,)


## 全て同じ値の配列の作成

In [24]:
# 1 を 100 個
sample_ndarray = np.ones(100)
print(sample_ndarray)
print(sample_ndarray.shape)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
(100,)


In [25]:
# 0 を 100 個
sample_ndarray = np.zeros(100)
print(sample_ndarray)
print(sample_ndarray.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
(100,)


In [26]:
# 7 を 100 個
sample_ndarray = np.full(100, 7)
print(sample_ndarray)
print(sample_ndarray.shape)

[7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7]
(100,)


## 要素の取り出し
ndarrayからの要素の取り出しにはリストと同じ方法が使えます。

In [44]:
sample_ndarray = np.arange(10)
print(sample_ndarray)
print('# 3番目の要素を取り出す:', sample_ndarray[3])
print('# 3番目の要素のひとつ前までを配列として取り出す:', sample_ndarray[:3])
print('# 一番最後の要素を取り出す:', sample_ndarray[-1])
print('# ステップ数2で、1つ飛ばしの配列を取り出す:', sample_ndarray[::2])
print('# 逆向きの配列を取り出す:', sample_ndarray[::-1])

[0 1 2 3 4 5 6 7 8 9]
# 3番目の要素を取り出す: 3
# 3番目の要素のひとつ前までを配列として取り出す: [0 1 2]
# 一番最後の要素を取り出す: 9
# ステップ数2で、1つ飛ばしの配列を取り出す: [0 2 4 6 8]
# 逆向きの配列を取り出す: [9 8 7 6 5 4 3 2 1 0]


## 形を変形する
配列の形を変えたい場合は、ndarrayの reshapeメソッド を使います。
> ##### メソッドとアトリビュート
> 形を変形させる機能```.reshape()```には括弧がつきますが、形を見る機能```.shape```には括弧が付きません。
> 前者が `メソッド` なのに対して、後者は `アトリビュート（属性）`
> メソッドは何らかの処理を行うため、引数をとれるように括弧が付きますが、アトリビュートは情報を返すだけ

In [54]:
a_ndarray = np.arange(4)
print(a_ndarray, a_ndarray.shape, a_ndarray.dtype, type(a_ndarray))

b_ndarray = a_ndarray.reshape(2, 2) #2行２列に変換(タプルで形を指定)
print(b_ndarray, b_ndarray.shape)

[0 1 2 3] (4,) int64 <class 'numpy.ndarray'>
[[0 1]
 [2 3]] (2, 2)


## 多次元での要素の取り出し
[Indexing — NumPy v1.16 Manual](https://numpy.org/doc/stable/user/basics.indexing.html)

In [62]:
sample_ndarray = np.arange(6).reshape(2, 3)
print(sample_ndarray, sample_ndarray.shape)

print('# 1行2列目の要素を取り出す:', sample_ndarray[1, 2]) #0indexに注意！
print('# 全ての行かつ1列目より後の列を配列として取り出す（スライス）\n', sample_ndarray[:, 1:])

[[0 1 2]
 [3 4 5]] (2, 3)
# 1行2列目の要素を取り出す: 5
# 全ての行かつ1列目より後の列を配列として取り出す（スライス）
 [[1 2]
 [4 5]]


## 平均や合計
引数に```axis=0```のように 軸 を指定すると、配列のある方向に対しての処理を行うことができます。

In [74]:
a_ndarray = np.arange(6)
b_ndarray = a_ndarray.reshape(2, 3)

print(a_ndarray, '\n', b_ndarray)
print('# shapeは{}'.format(b_ndarray.shape))
print('# 合計値は{}'.format(b_ndarray.sum()))
print('# 0番目の軸方向の合計は{}'.format(b_ndarray.sum(axis=0))) #軸は列計算
print('# 1番目の軸方向の合計は{}'.format(b_ndarray.sum(axis=1))) #軸は行計算
print('# 1番目の軸方向の平均は{}'.format(b_ndarray.mean(axis=1)))

[0 1 2 3 4 5] 
 [[0 1 2]
 [3 4 5]]
# shapeは(2, 3)
# 合計値は15
# 0番目の軸方向の合計は[3 5 7]
# 1番目の軸方向の合計は[ 3 12]
# 1番目の軸方向の平均は[1. 4.]
